// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
  integrations: [{ type: 'autogenerated', dirName: 'integrations' }],
  videolessons: [{ type: 'autogenerated', dirName: 'videolessons' }],
  updates: [{ type: 'autogenerated', dirName: 'updates' }],
  'docs-en': [
    {
      'Getting started': [
        'en/getting-started/en-getting-started-with-sendsay',
        'en/getting-started/en-how-to-migrate-to-sendsay',
      ],
    },
    {
      'Email campaigns': [
        'en/email-campaigns/en-drag-and-drop-editor',
        'en/email-campaigns/en-how-to-send-email-campaign',
      ],
    },
    {
      Forms: ['en/forms/en-signup-forms'],
    },
    {
      Subscribers: [
        'en/subscribers/en-how-to-import-subscribers',
        'en/subscribers/en-how-to-prepare-file-for-import',
      ],
    },
    {
      'Other channels': [
        'en/other-channels/en-how-to-connect-sms',
        'en/other-channels/en-how-to-connect-web-push',
        'en/other-channels/en-how-to-create-web-push-campaign',
      ],
    },
  ],
};

module.exports = sidebars;
